[build]
  functions = "netlify/functions"
  publish = "build"

[template.environment]
  PAYPAL_CLIENT_ID = ""
  PAYPAL_SECRET = ""

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200
