[build]
  functions = "netlify/functions"
  publish = "dist" # or "build" depending on your React setup

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200
